### ISSUE TITLE
NullpointerException bei leerem Zug

### ISSUE THREAD

**Issue by soerendomroes** [CAU-Kiel-Tech-Inf/socha#112]
java.lang.NullPointerException
	at sc.plugin2018.Move.perform(Move.java:177) [na:na]
	at sc.plugin2018.Game.onRoundBasedAction(Game.java:83) [na:na]
	at sc.framework.plugins.RoundBasedGameInstance.onAction(RoundBasedGameInstance.java:76) [software_challenge-sdk.jar:na]
	at sc.server.gaming.GameRoom.onEvent(GameRoom.java:532) [softwarechallenge-server.jar:na]
	at sc.server.Lobby.onRequest(Lobby.java:119) [softwarechallenge-server.jar:na]
	at sc.server.network.Client.notifyOnPacket(Client.java:116) [softwarechallenge-server.jar:na]
	at sc.server.network.Client.onObject(Client.java:297) [softwarechallenge-server.jar:na]
	at sc.networking.clients.XStreamClient.receiveThread(XStreamClient.java:132) [software_challenge-sdk.jar:na]
	at sc.networking.clients.XStreamClient$1.run(XStreamClient.java:87) [software_challenge-sdk.jar:na]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_121]

**Comment by soerendomroes** [comment]
fixed by 62600e10b6873776470bc8049a92617d5147010f
