### ISSUE TITLE
Problem mit Pausemodus

### ISSUE THREAD

**Issue by soerendomroes** [CAU-Kiel-Tech-Inf/socha#117]
Beim starten des Spiels ohne Gui mit zwei Computerpsielern im Pausemodus, scheint der erste Spieler beim starten des Spiels (pause=false) mit einem PauseRequest immer zwei MoveRequests zu bekommen. Einen initial und einen nach dem starten.

**Comment by soerendomroes** [comment]
```
08:43:00 INFO  sc.server.Application - Server is starting up...
08:43:00 INFO  sc.server.Application - Registering ShutdownHook (Ctrl+C)...
08:43:00 ERROR sc.server.Application - loading server.properties
08:43:01 INFO  sc.server.plugins.PluginManager - Loading plugins from: /home/soed/Dokumente/socha/deploy/server/./plugins
08:43:01 DEBUG sc.server.plugins.PluginManager - Loading: Hase und Igel
08:43:01 INFO  sc.server.plugins.GamePluginInstance - GamePlugin 'Hase und Igel' {swc_2018_hase_und_igel} was loaded.
08:43:01 INFO  sc.server.plugins.PluginManager - Plugin-Cache reloaded. 1 plugins available.
08:43:01 INFO  sc.server.gaming.GamePluginApi - Processing XStream annotations for class sc.plugin2018.Game
08:43:01 INFO  sc.server.gaming.GamePluginApi - Processing XStream annotations for class sc.plugin2018.Board
08:43:01 INFO  sc.server.gaming.GamePluginApi - Processing XStream annotations for class sc.plugin2018.GameState
08:43:01 INFO  sc.server.gaming.GamePluginApi - Processing XStream annotations for class sc.plugin2018.Move
08:43:01 INFO  sc.server.gaming.GamePluginApi - Processing XStream annotations for class sc.plugin2018.Player
08:43:01 INFO  sc.server.gaming.GamePluginApi - Processing XStream annotations for class sc.shared.WelcomeMessage
08:43:01 INFO  sc.server.gaming.GamePluginApi - Processing XStream annotations for class sc.plugin2018.CardType
08:43:01 INFO  sc.server.gaming.GamePluginApi - Processing XStream annotations for class sc.plugin2018.FieldType
08:43:01 INFO  sc.server.gaming.GamePluginApi - Processing XStream annotations for class sc.plugin2018.Advance
08:43:01 INFO  sc.server.gaming.GamePluginApi - Processing XStream annotations for class sc.plugin2018.Action
08:43:01 INFO  sc.server.gaming.GamePluginApi - Processing XStream annotations for class sc.plugin2018.Skip
08:43:01 INFO  sc.server.gaming.GamePluginApi - Processing XStream annotations for class sc.shared.PlayerColor
08:43:01 INFO  sc.server.gaming.GamePluginApi - Processing XStream annotations for class sc.plugin2018.Card
08:43:01 INFO  sc.server.gaming.GamePluginApi - Processing XStream annotations for class sc.plugin2018.EatSalad
08:43:01 INFO  sc.server.gaming.GamePluginApi - Processing XStream annotations for class sc.plugin2018.ExchangeCarrots
08:43:01 INFO  sc.server.gaming.GamePluginApi - Processing XStream annotations for class sc.plugin2018.FallBack
08:43:01 INFO  sc.server.gaming.GamePluginApi - Processing XStream annotations for interface java.util.concurrent.locks.Condition
08:43:01 INFO  sc.server.network.NewClientListener - Listening on port 13050 for incoming connections.
08:43:01 DEBUG sc.server.ServiceManager - Spawning thread for new service (name=NewClientListener, daemon=true)
08:43:01 DEBUG sc.server.ServiceManager - Spawning thread for new service (name=ClientManager, daemon=true)
08:43:01 INFO  sc.server.Application - Server has been initialized in 215 ms.
08:43:01 INFO  sc.server.network.ClientManager - ClientManager running.
08:43:04 INFO  sc.server.network.NewClientListener - A Client connected...
08:43:04 INFO  sc.server.network.NewClientListener - Added Client sc.server.network.Client@1d506a81 to ReadyQueue.
08:43:04 INFO  sc.server.network.ClientManager - Delegating new client to ClientManager...
08:43:04 INFO  sc.server.network.ClientManager - Delegation done.
08:43:11 INFO  sc.networking.clients.XStreamClient - Client sc.server.network.Client@1d506a81: Received sc.protocol.requests.AuthenticateRequest@55151157 via sc.networking.TcpNetwork@75dfe4fb
DataDump:
<authenticate passphrase="examplepassword"/>
08:43:11 INFO  sc.server.network.Client - Client authenticated as administrator
08:43:44 INFO  sc.server.network.NewClientListener - A Client connected...
08:43:44 INFO  sc.server.network.NewClientListener - Added Client sc.server.network.Client@6e433d1d to ReadyQueue.
08:43:44 INFO  sc.server.network.ClientManager - Delegating new client to ClientManager...
08:43:44 INFO  sc.server.network.ClientManager - Delegation done.
08:43:44 INFO  sc.networking.clients.XStreamClient - Client sc.server.network.Client@6e433d1d: Received sc.protocol.requests.JoinRoomRequest@50074649 via sc.networking.TcpNetwork@5ec0b239
DataDump:
<join gameType="swc_2018_hase_und_igel"/>
08:43:44 INFO  sc.server.gaming.GameRoomManager - Created new game of type swc_2018_hase_und_igel
08:43:44 INFO  sc.server.gaming.GameRoom - Switching PAUSE from false to true.
08:43:44 INFO  sc.server.gaming.GameRoomManager - Pause is set to true
08:43:44 DEBUG sc.server.gaming.GameRoomManager - Adding room with id f06f6bcd-2f52-442e-857c-9e2d80fb2492
08:43:44 DEBUG sc.server.gaming.GameRoom - GameRoom was not prepared, syncSlots
08:43:44 DEBUG sc.server.gaming.GameRoom - startIfReady called
08:43:44 INFO  sc.server.gaming.GameRoom - Game isn't ready yet.
08:44:09 INFO  sc.networking.clients.XStreamClient - Client sc.server.network.Client@1d506a81: Received sc.protocol.requests.ObservationRequest@63cbaa3e via sc.networking.TcpNetwork@75dfe4fb
DataDump:
<observe roomId="f06f6bcd-2f52-442e-857c-9e2d80fb2492"/>
08:44:13 INFO  sc.server.network.NewClientListener - A Client connected...
08:44:13 INFO  sc.server.network.NewClientListener - Added Client sc.server.network.Client@626e19de to ReadyQueue.
08:44:13 INFO  sc.server.network.ClientManager - Delegating new client to ClientManager...
08:44:13 INFO  sc.server.network.ClientManager - Delegation done.
08:44:13 INFO  sc.networking.clients.XStreamClient - Client sc.server.network.Client@626e19de: Received sc.protocol.requests.JoinRoomRequest@1b454697 via sc.networking.TcpNetwork@1582bb8f
DataDump:
<join gameType="swc_2018_hase_und_igel"/>
08:44:13 DEBUG sc.server.gaming.GameRoom - GameRoom was not prepared, syncSlots
08:44:13 DEBUG sc.server.gaming.GameRoom - startIfReady called
08:44:13 INFO  sc.server.gaming.GameRoom - Updating Status to ACTIVE (was: CREATED)
08:44:13 DEBUG sc.server.gaming.GameRoom - sending state to observer sc.server.network.Client@1d506a81
08:44:13 INFO  sc.server.gaming.GameRoom - Started the game.
08:44:13 INFO  sc.networking.clients.XStreamClient - Client sc.server.network.Client@6e433d1d: Received sc.protocol.responses.RoomPacket@935f3f1 via sc.networking.TcpNetwork@5ec0b239
DataDump:
<room roomId="f06f6bcd-2f52-442e-857c-9e2d80fb2492">
  <data class="move">
    <advance order="0" distance="7"/>
    <card order="1" type="EAT_SALAD" value="0"/>
  </data>
</room>
08:44:13 INFO  sc.framework.plugins.ActionTimeout - Time needed: 14
08:44:13 INFO  s.f.plugins.RoundBasedGameInstance - Game is paused. Save this action.
08:44:13 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
08:44:13 DEBUG sc.server.gaming.GameRoom - sending RoomPacket to observer Client
08:45:07 INFO  sc.networking.clients.XStreamClient - Client sc.server.network.Client@1d506a81: Received sc.protocol.requests.PauseGameRequest@22253cc1 via sc.networking.TcpNetwork@75dfe4fb
DataDump:
<pause roomId="f06f6bcd-2f52-442e-857c-9e2d80fb2492" pause="false"/>
08:45:07 INFO  sc.server.gaming.GameRoom - Switching PAUSE from true to false.
08:45:07 INFO  s.f.plugins.RoundBasedGameInstance - Run AfterPauseAction.
08:45:07 DEBUG sc.server.gaming.GameRoom - sending state to observer sc.server.network.Client@1d506a81
08:45:07 INFO  sc.networking.clients.XStreamClient - Client sc.server.network.Client@6e433d1d: Received sc.protocol.responses.RoomPacket@4d31e498 via sc.networking.TcpNetwork@5ec0b239
DataDump:
<room roomId="f06f6bcd-2f52-442e-857c-9e2d80fb2492">
  <data class="move">
    <advance order="0" distance="2"/>
    <card order="1" type="EAT_SALAD" value="0"/>
  </data>
</room>
08:45:07 WARN  sc.server.network.Client - An error occured: 
sc.api.plugins.exceptions.GameLogicException: It's not your turn yet.
	at sc.framework.plugins.RoundBasedGameInstance.onAction(RoundBasedGameInstance.java:102) [bin/:na]
	at sc.server.gaming.GameRoom.onEvent(GameRoom.java:532) [bin/:na]
	at sc.server.Lobby.onRequest(Lobby.java:119) [bin/:na]
	at sc.server.network.Client.notifyOnPacket(Client.java:116) [bin/:na]
	at sc.server.network.Client.onObject(Client.java:297) [bin/:na]
	at sc.networking.clients.XStreamClient.receiveThread(XStreamClient.java:132) [bin/:na]
	at sc.networking.clients.XStreamClient$1.run(XStreamClient.java:87) [bin/:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
08:45:07 DEBUG sc.server.network.Client - stopping client because of error. Thread: XStreamClient Receive Thread 14 Client
08:45:07 INFO  sc.networking.clients.XStreamClient - Client sc.server.network.Client@6e433d1d disconnected (Cause: DISCONNECTED)
08:45:07 INFO  sc.networking.clients.XStreamClient - Stopping receiver thread XStreamClient Receive Thread 14 Client
08:45:07 WARN  sc.networking.clients.XStreamClient - receiver thread is stopping itself
08:45:07 INFO  sc.server.gaming.GameRoom - Removing Player Unknown (color,index,carrots,salads) (RED,0,68,5)
TAKE_OR_DROP_CARROTS
EAT_SALAD
HURRY_AHEAD
FALL_BACK
LastAction null from sc.server.gaming.GameRoom@29f0fb1e
08:45:07 INFO  sc.networking.clients.XStreamClient - Client sc.server.network.Client@626e19de: Received sc.protocol.responses.RoomPacket@63b6e662 via sc.networking.TcpNetwork@1582bb8f
DataDump:
<room roomId="f06f6bcd-2f52-442e-857c-9e2d80fb2492">
  <data class="move">
    <advance order="0" distance="7"/>
    <card order="1" type="EAT_SALAD" value="0"/>
  </data>
</room>
08:45:07 INFO  sc.framework.plugins.ActionTimeout - Time needed: 15
08:45:07 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
08:45:07 DEBUG sc.server.gaming.GameRoom - sending state to observer sc.server.network.Client@1d506a81
08:45:07 WARN  sc.server.network.Client - Writing on a closed Stream -> dropped the packet. (tried to send package of type RoomPacket) Thread: XStreamClient Receive Thread 15 Client
08:45:07 INFO  sc.networking.clients.XStreamClient - Client sc.server.network.Client@626e19de: Received sc.protocol.responses.RoomPacket@491097fc via sc.networking.TcpNetwork@1582bb8f
DataDump:
<room roomId="f06f6bcd-2f52-442e-857c-9e2d80fb2492">
  <data class="move">
    <advance order="0" distance="10"/>
  </data>
</room>
08:45:07 INFO  sc.server.gaming.GameRoom - Updating Status to OVER (was: ACTIVE)
08:45:07 INFO  sc.server.gaming.GameRoom - The game f06f6bcd-2f52-442e-857c-9e2d80fb2492 is over. (regular=false)
08:45:07 DEBUG sc.server.gaming.GameRoom - sending GameResult to Client
08:45:07 WARN  sc.server.network.Client - Writing on a closed Stream -> dropped the packet. (tried to send package of type RoomPacket) Thread: XStreamClient Receive Thread 14 Client
08:45:07 DEBUG sc.server.gaming.GameRoom - sending GameResult to Client
08:45:07 DEBUG sc.server.gaming.GameRoom - sending RoomPacket to observer Client
08:45:07 DEBUG sc.server.gaming.GameRoom - Kicking clients (and observer)
08:45:07 DEBUG sc.server.gaming.GameRoom - sending LeftGameEvent to Client
08:45:07 WARN  sc.server.network.Client - Writing on a closed Stream -> dropped the packet. (tried to send package of type LeftGameEvent) Thread: XStreamClient Receive Thread 14 Client
08:45:07 DEBUG sc.server.gaming.GameRoom - sending LeftGameEvent to Client
08:45:07 DEBUG sc.server.gaming.GameRoom - sending LeftGameEvent to observer Client
08:45:07 INFO  s.f.plugins.RoundBasedGameInstance - Destroying Game
08:45:07 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
08:45:07 WARN  sc.server.network.Client - An error occured: 
sc.api.plugins.exceptions.RescuableClientException: Game is already over, but got data: class sc.plugin2018.Move
	at sc.server.gaming.GameRoom.onEvent(GameRoom.java:529) [bin/:na]
	at sc.server.Lobby.onRequest(Lobby.java:119) [bin/:na]
	at sc.server.network.Client.notifyOnPacket(Client.java:116) [bin/:na]
	at sc.server.network.Client.onObject(Client.java:297) [bin/:na]
	at sc.networking.clients.XStreamClient.receiveThread(XStreamClient.java:132) [bin/:na]
	at sc.networking.clients.XStreamClient$1.run(XStreamClient.java:87) [bin/:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
08:45:07 WARN  sc.server.network.Client - Game closed because of GameLogicException! The message is: Game is already over, but got data: class sc.plugin2018.Move
08:45:07 DEBUG sc.server.network.Client - stopping client because of error. Thread: XStreamClient Receive Thread 15 Client
08:45:07 INFO  sc.networking.clients.XStreamClient - Client sc.server.network.Client@626e19de disconnected (Cause: DISCONNECTED)
08:45:07 INFO  sc.networking.clients.XStreamClient - Stopping receiver thread XStreamClient Receive Thread 15 Client
08:45:07 WARN  sc.networking.clients.XStreamClient - receiver thread is stopping itself
08:45:07 INFO  sc.server.gaming.GameRoom - Removing Player Unknown (color,index,carrots,salads) (BLUE,0,68,5)
TAKE_OR_DROP_CARROTS
EAT_SALAD
HURRY_AHEAD
FALL_BACK
LastAction null from sc.server.gaming.GameRoom@29f0fb1e
08:45:07 WARN  sc.server.gaming.GameRoom - Game was already over but received another GameOver-Event.
08:45:07 INFO  sc.server.network.ClientManager - Removing client sc.server.network.Client@626e19de from client manager
08:45:07 INFO  sc.server.Lobby - sc.server.network.Client@626e19de disconnected.
08:45:07 INFO  sc.server.network.ClientManager - Removing client sc.server.network.Client@6e433d1d from client manager
08:45:07 INFO  sc.server.Lobby - sc.server.network.Client@6e433d1d disconnected.
08:45:17 WARN  s.f.plugins.RoundBasedGameInstance - Player Player Unknown (color,index,carrots,salads) (RED,7,50,4)
TAKE_OR_DROP_CARROTS
HURRY_AHEAD
FALL_BACK
LastAction Card EAT_SALAD order 1 reached the timeout of 10000ms
08:45:17 WARN  sc.server.gaming.GameRoom - Game was already over but received another GameOver-Event.
```

**Comment by SKoschnicke** [comment]
Man wuerde ja auch eigentlich erwarten, dass ein Spiel welches pausiert startet, erstmal gar keinen Move Request erzeugt. Und dann erst einen wenn ein Step kommt oder die Pause aufgehoben wird.

**Comment by soerendomroes** [comment]
Idee: Pause nur zwischen den Zügen anwenden, damit Zug nicht innerhalb der Pause eingehen kann.

**Comment by soerendomroes** [comment]
Idee: Nicht boolean pause, sondern die Runde ab der pausiert wird.
