### ISSUE TITLE
Exception am Ende eines Spiels

### ISSUE THREAD

**Issue by Xerus2000** [CAU-Kiel-Tech-Inf/socha#145]
````
[XStreamClient Receive Thread 12 LobbyClient] WARN  sc.networking.clients.XStreamClient - receiver thread is stopping itself
Exception in thread "XStreamClient Receive Thread 12 LobbyClient" java.lang.NoClassDefFoundError: ch/qos/logback/classic/spi/ThrowableProxy
        at ch.qos.logback.classic.spi.LoggingEvent.<init>(LoggingEvent.java:111)
        at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:437)
        at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:393)
        at ch.qos.logback.classic.Logger.error(Logger.java:556)
        at sc.networking.clients.XStreamClient.close(XStreamClient.java:276)
        at sc.networking.clients.XStreamClient.handleDisconnect(XStreamClient.java:223)
        at sc.networking.clients.XStreamClient.receiveThread(XStreamClient.java:151)
        at sc.networking.clients.XStreamClient$1.run(XStreamClient.java:85)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: ch.qos.logback.classic.spi.ThrowableProxy
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 9 more
```

**Comment by SKoschnicke** [comment]
Passiert das immer oder vereinzelnt? Welche Version von logback wird verwendet?

**Comment by Xerus2000** [comment]
Ich werde nochmal schauen, aber bei mir ist das zumindest ne zeitlang regelmäßig passiert. In der Logik am Ende des Spiels, wo sich TestClient und Server trennen, scheint es aber sowieso noch einige Problemchen zu geben.

**Comment by Xerus2000** [comment]
Ich schließe das mal bis auf weiteres.
