### ISSUE TITLE
observationRequest Test schlaegt manchmal fehl

### ISSUE THREAD

**Issue by SKoschnicke** [CAU-Kiel-Tech-Inf/socha#147]
Passiert immer mal, wenn man alle Tests in IntelliJ ausfuehrt. Folgende Exception tritt auf:
```
14:31:01 ERROR sc.networking.clients.XStreamClient - Unknown Communication Error
java.util.ConcurrentModificationException
	at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:966) [na:1.8.0_144]
	at java.util.LinkedList$ListItr.next(LinkedList.java:888) [na:1.8.0_144]
	at sc.server.network.Client.isAdministrator(Client.java:220) [bin/:na]
	at sc.server.Lobby.onRequest(Lobby.java:91) [bin/:na]
	at sc.server.network.Client.notifyOnPacket(Client.java:117) [bin/:na]
	at sc.server.network.Client.onObject(Client.java:298) [bin/:na]
	at sc.networking.clients.XStreamClient.receiveThread(XStreamClient.java:130) [bin/:na]
	at sc.networking.clients.XStreamClient$1.run(XStreamClient.java:85) [bin/:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_144]
```

**Comment by Xerus2000** [comment]
Scheint nicht mehr aufzutreten
