### ISSUE TITLE
Probleme mit XStream und Deserialisieren in DataClasses

### ISSUE THREAD

**Issue by SKoschnicke** [CAU-Kiel-Tech-Inf/socha#220]
Der SimpleClient bekommt jede Menge NullPointerExceptions fuer Datenstrukturen, die eigentlich nicht null werden sollten:

```
21:15:42 ERROR sc.networking.clients.XStreamClient - Unknown Communication Error
java.lang.NullPointerException: null
	at sc.plugin2020.GameState.getDeployedPieces(GameState.kt:86)
	at sc.plugin2020.util.GameRuleLogic.hasPlayerPlacedBee(GameRuleLogic.kt:303)
	at sc.plugin2020.util.GameRuleLogic.getPossibleSetMoves(GameRuleLogic.kt:363)
	at sc.plugin2020.util.GameRuleLogic.getPossibleMoves(GameRuleLogic.kt:311)
	at sc.player2020.logic.Logic.onRequestAction(Logic.java:52)
	at sc.plugin2020.AbstractClient.onRoomMessage(AbstractClient.java:90)
	at sc.networking.clients.LobbyClient.onRoomMessage(LobbyClient.java:244)
	at sc.networking.clients.LobbyClient.onObject(LobbyClient.java:95)
	at sc.networking.clients.XStreamClient.receiveThread(XStreamClient.java:115)
	at sc.networking.clients.XStreamClient$1.run(XStreamClient.java:77)
	at java.lang.Thread.run(Thread.java:748)
```

```
21:28:32 ERROR sc.networking.clients.XStreamClient - Unknown Communication Error
java.lang.NullPointerException: null
	at sc.plugin2020.Field.isEmpty(Field.kt:34)
	at sc.plugin2020.util.GameRuleLogic.getPossibleSetMoves(GameRuleLogic.kt:352)
	at sc.plugin2020.util.GameRuleLogic.getPossibleMoves(GameRuleLogic.kt:311)
	at sc.player2020.logic.Logic.onRequestAction(Logic.java:52)
	at sc.plugin2020.AbstractClient.onRoomMessage(AbstractClient.java:90)
	at sc.networking.clients.LobbyClient.onRoomMessage(LobbyClient.java:244)
	at sc.networking.clients.LobbyClient.onObject(LobbyClient.java:95)
	at sc.networking.clients.XStreamClient.receiveThread(XStreamClient.java:115)
	at sc.networking.clients.XStreamClient$1.run(XStreamClient.java:77)
	at java.lang.Thread.run(Thread.java:748)
```

Ich vermute das haengt mit einer seltsamen Weise zusammen, wie XStream die Objekte aus dem XML anlegt. Da werden die Initialisierungen nicht richtig gemacht, und dann haben wir statt eines `Stack()` fuer `pieces` einfach nur `null`.

**Comment by SKoschnicke** [comment]
Die Fehler sieht man wenn man die tests im Build-Script wieder aktiviert und dann in die Client-Logs in build/tests guckt.
